/Users/xinyuan/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.31.164:5001
[33mPress CTRL+C to quit[0m
 * Restarting with stat
/Users/xinyuan/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
 * Debugger is active!
 * Debugger PIN: 272-915-924
Traceback (most recent call last):
  File "/Users/xinyuan/Desktop/è¯„è®ºæ£€ç´¢/app.py", line 304, in <module>
    app.run(debug=True, host='0.0.0.0', port=5001) 
  File "/Users/xinyuan/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 889, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/Users/xinyuan/Library/Python/3.9/lib/python/site-packages/werkzeug/serving.py", line 1097, in run_simple
    run_with_reloader(
  File "/Users/xinyuan/Library/Python/3.9/lib/python/site-packages/werkzeug/_reloader.py", line 446, in run_with_reloader
    ensure_echo_on()
  File "/Users/xinyuan/Library/Python/3.9/lib/python/site-packages/werkzeug/_reloader.py", line 426, in ensure_echo_on
    termios.tcsetattr(sys.stdin, termios.TCSANOW, attributes)
termios.error: (4, 'Interrupted system call')
